---
- name: Reboot System
  ansible.builtin.reboot:
  when:
    - skip_handlers | default("false") == "false"

- name: microk8s ready
  ansible.builtin.command:
    cmd: microk8s.status --wait-ready
  changed_when: false
  when:
    - skip_handlers | default("false") == "false"

- name: refresh user config
  include_tasks: ../tasks/configure-groups.yml
  when:
    - skip_handlers | default("false") == "false"

- name: restart microk8s
  ansible.builtin.shell: |
    microk8s stop && microk8s start && microk8s.status --wait-ready

...
